name: 'Kb Pull Request Deployment Badges'
description: 'Add deployment links to PR body as badges'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  badge-left:
    description: Left-Hand side text of badge
    required: false
    default: demo
  badge-right:
    description: Right-Hand side text of badge
    required: false
    default: application
  badge-color:
    description: Right-Hand side css color
    required: false
    default: informational
  badge-logo:
    description: Badge Logo
    required: false
    default: ''
  badge-path:
    description: Path to navigate to in deployment
    required: false
    default: ''
  badge2-left:
    description: Left-Hand side text of badge
    required: false
  badge2-right:
    description: Right-Hand side text of badge
    required: false
  badge2-color:
    description: Right-Hand side css color
    required: false
  badge2-logo:
    description: Badge Logo
    required: false
  badge2-path:
    description: Path to navigate to in deployment
    required: false
  badge3-left:
    description: Left-Hand side text of badge
    required: false
  badge3-right:
    description: Right-Hand side text of badge
    required: false
  badge3-color:
    description: Right-Hand side css color
    required: false
  badge3-logo:
    description: Badge Logo
    required: false
  badge3-path:
    description: Path to navigate to in deployment
    required: false
outputs:
  time: # id of output
    description: The time the action finished
runs:
  using: 'node12'
  main: 'index.js'